name: 'VSC, THE BETA'
favicon: null
layout_spectrum: 0.8
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ebeff7'
    - '#303340'
    - '#020104'
    - '#da9e88'
    - '#94604f'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose:
  - name: awareness
    item: null
    url: 'VSC is a Strategic Communications Firm '
