name: 'VSC, THE BETA'
favicon: null
layout_spectrum: 0.23103
typography_spectrum: 0.22759
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e7e9eb'
    - '#000000'
    - '#2d262a'
    - '#d6ad99'
    - '#908d90'
  brandStrength: 0.9375
  lightness: 0.5
  saturation: 0.9375
  rhythmicContrast: 0.5
purpose:
  - name: awareness
    item: null
    url: 'VSC is a Strategic Communications Firm '
